name: Generate Pac-Man Contribution Game

on:
  schedule:
    - cron: "0 0 * * *"   # roda todo dia à meia-noite (corrigido: 5 campos)
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # versão mais recente
        
      - name: Generate Pac‑Man graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Publish to branch output
        uses: crazy-max/ghaction-github-pages@v4  # versão mais recente
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
